### ISSUE TITLE
How to config conf.py

### ISSUE THREAD

**Issue by chenboshuo** [Czaki/sphinx-qt-documentation#31]
I tried to add
```python
import sphinx_qt_documentation
```

and
```python
qt_documentation=PyQt5
```
However, they don't work, I don't understand this beginning guide.
Can you help me? Thank you for your attention.

**Comment by Czaki** [comment]
You need to add `"sphinx_qt_documentation"` to `extensions` in `conf.py`, like here:
https://github.com/4DNucleome/PartSeg/blob/develop/docs/conf.py#L40

**Comment by chenboshuo** [comment]
Maybe I also lost some modules
```
Extension error:
Could not import extension sphinx_qt_documentationsphinx.ext.autosectionlabel (exception: No module named 'sphinx_qt_documentationsphinx')
make: *** [Makefile:20: html] Error 2
```

**Comment by Czaki** [comment]
It looks like you forget to add ',' after `"sphinx_qt_documentation"` and python concatenate two strings in one.

**Comment by chenboshuo** [comment]
Such a simple error, I corrected it, thank you for your patience.
