### ISSUE TITLE
How to cross-link to enum members in Qt6 docs?

### ISSUE THREAD

**Issue by j9ac9k** [Czaki/sphinx-qt-documentation#33]
Hello,

pyqtgraoh maintainer here, love this package, it has made our documentation so much better, thank you for maintaining and publishing this library!

I do have a question, how should I link to specific qt-enum members? I'm trying to link to `QtWidgets.QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations`

All the following generate reference not found target warnings.

```python
# conf.py
qt_documentation = "Qt6"
```

Attempts at corss-linking without success:

```rst
        :func:`QtWidgets.QGraphicsItem.ItemIgnoresTransformations`
        :meth:`QtWidgets.QGraphicsItem.ItemIgnoresTransformations`
        :mod:`QtWidgets.QGraphicsItem.ItemIgnoresTransformations`
        :const:`QtWidgets.QGraphicsItem.ItemIgnoresTransformations`
        :data:`QtWidgets.QGraphicsItem.ItemIgnoresTransformations`
        :class:`QtWidgets.QGraphicsItem.ItemIgnoresTransformations`
        :attr:`QtWidgets.QGraphicsItem.ItemIgnoresTransformations`
        :obj:`QtWidgets.QGraphicsItem.ItemIgnoresTransformations`
        :cpp:enum:`QtWidgets::QGraphicsItem::ItemIgnoresTransformations`
        :func:`QtWidgets.QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations`
        :meth:`QtWidgets.QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations`
        :mod:`QtWidgets.QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations`
        :const:`QtWidgets.QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations`
        :data:`QtWidgets.QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations`
        :class:`QtWidgets.QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations`
        :attr:`QtWidgets.QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations`
        :obj:`QtWidgets.QGraphicsItem.GraphicsItemFlag.ItemIgnoresTransformations`
        :cpp:enum:`QtWidgets::QGraphicsItem::GraphicsItemFlag::ItemIgnoresTransformations`
```

I should note my sphinx game is fairly weak, so I could be missing something obvious.

EDIT: I just realized that this enum member doesn't have a link within the web documentation, which is probably why it's not working.

**Comment by Czaki** [comment]
Could you point part of codebase? Or best, some really small example.
 I think that I should be able to make it link to enum itself https://doc.qt.io/qt-6/qgraphicsitem.html#GraphicsItemFlag-enum 

As I checked, it is not possible to lint to item, as there is no such anchor on the webpage.

**Comment by j9ac9k** [comment]
Thanks for checking @Czaki  ...the moment I realized there was no anchor, I realized what I was asking for was unrealistic.  I apologize for the noise!
