### ISSUE TITLE
KeyError: 'PyQt5'

### ISSUE THREAD

**Issue by gregcouch** [Czaki/sphinx-qt-documentation#5]
Hi,

I installed sphinx-qt-documentation 0.2 from PyPi for Python 3.  And then added sphinx_qt_documentation to my sphinx conf.py list of extensions.  Nothing else.  And now, when I run sphinx, I get:
```
Exception occurred:
  File "..../lib/python3.7/site-packages/sphinx_qt_documentation/__init__.py", line 108, in missing_reference
    for name in inventories.named_inventory["PyQt5"]["sip:module"].keys()
KeyError: 'PyQt5'
```
It failed with Sphinx 2.3.1 and 2.4.1.  The full list of extensions is:
```
     'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    'sphinx.ext.autosummary',
    'sphinx.ext.extlinks',
    'numpydoc',
    'sphinx_qt_documentation',
```

**Comment by Czaki** [comment]
On the begining of execution it needs to download objects.inv from PyQt5 web server. 

Could you check if there is some information about download failure? 
Could you manually check if you can download https://www.riverbankcomputing.com/static/Docs/PyQt5/objects.inv

**Comment by Czaki** [comment]
@gregcouch Any information?

**Comment by Czaki** [comment]
No information which allows to reproduce problem.

**Comment by bicobus** [comment]
This happened to me the first time I ran sphinx. Any subsequent build would then succeed.
