### ISSUE TITLE
Broken on Python 3.5, which is default on *buntu 16.04 LTS

### ISSUE THREAD

**Issue by ssokolow** [Czaki/sphinx-qt-documentation#6]
You're currently depending on formatted string literals, which require a minimum of Python 3.6, yet distros like *buntu 16.04 LTS which ship Python 3.5 haven't fallen out of support yet.

```
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/sphinx_qt_documentation/__init__.py", line 35
    core = importlib.import_module(f'{module_name}.QtCore')
                                                         ^
SyntaxError: invalid syntax
```

I tried pinning it to version 0.1 but found that you're also depending on annotated assignment statements, which were also first available in Python 3.6.

```
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/sphinx_qt_documentation/__init__.py", line 61
    target: str = node["reftarget"]
          ^
SyntaxError: invalid syntax
```

While editing a copy of your 0.2 to vendor into my codebase, I also noticed this line:

```
        except (ModuleNotFoundError, ImportError):
```

Aside from breaking Python 3.5, it's unnecessary. `ModuleNotFoundError` is a subclass of `ImportError`, so `except ImportError` will catch it.

Once I finished fixing those, as well as various complaints my PyLint+Flake8+MyPy on-save static analysis had, I slammed into this error:

```
  File "/home/ssokolow/Documents/Critical/src/quick_tesseract/docs/sphinx_qt_documentation/__init__.py", line 118, in missing_reference
    for name in (inventories.named_inventory["PyQt5"]
KeyError: 'PyQt5'
```

...and, since I didn't sleep well and I'm not very familiar with what your code is trying to do, I haven't solved that yet.

**Comment by ssokolow** [comment]
```
  File "/home/ssokolow/Documents/Critical/src/quick_tesseract/docs/sphinx_qt_documentation/__init__.py", line 118, in missing_reference
    for name in (inventories.named_inventory["PyQt5"]
KeyError: 'PyQt5'
```

...it appears to be a bug in how your `setup` inserts a default value into Sphinx, because adding this to my `conf.py` manually fixed it:

    'PyQt5': ('https://www.riverbankcomputing.com/static/Docs/PyQt5', None),

As for my other changes, if you'd like, I could put up a PR for you to consider.

**Comment by Czaki** [comment]
Please open PR. Remember about tests

**Comment by ssokolow** [comment]
Will do.

Sorry for the delayed response. The last couple of days were surprisingly busy.

**Comment by Czaki** [comment]
No problem. All my projects are python 3.6+ so I'm not familiar with python 3.5 limitations.

**Comment by ssokolow** [comment]
Sorry for going silent. A bunch of stuff came up including having one of my sites broken by a PHP upgrade on the shared hosting it's on.

Aside from figuring out how to run the tests, the change should already have been made when I said "Will do.", so I'll try to get you a PR within the next few days.

**Comment by ssokolow** [comment]
Sorry for going silent... again. I really shouldn't give time-frames. It dares life to make a mess of things.

I'm having trouble getting your tests to succeed locally. I whipped up a little `test_local.sh` script to set up for and run your `.ci/run_tests.bash`, but the non-`no_install` test is failing with `RuntimeError: No Qt bindings found` despite `from PyQt5 import QtCore` working just fine in the test virtualenv.

**Comment by Czaki** [comment]
Did you use same environment for all test, or recreate it from scratch? 

Because this test assume that there are no qt bindings, And if they are installed earlier then import pass.

**Comment by ssokolow** [comment]
Here's the relevant part of my script:

```sh
# -- Ensure virtualenvs are created --
if [ ! -e venv ]; then
    virtualenv -p python3 venv
fi
if [ ! -e venv_sys ]; then
    virtualenv -p python3 --system-site-packages venv_sys
fi

# -- Run both tests defined in run_tests.bash --
. ./venv/bin/activate
bash .ci/run_tests.bash no_install || accum_fail "No Qt"
deactivate

. ./venv_sys/bin/activate
bash .ci/run_tests.bash "" || accum_fail "Qt Installed"
deactivate
```

**Comment by Czaki** [comment]
I see that you recreate venv only if they are missed. What if You delete it manually? (remove dir venv)

**Comment by ssokolow** [comment]
I already tried that and it made no difference, however something was tickling at my memory and, looking at the project where I committed a vendored copy of my changes, I realized that this isn't a bug I introduced.

I had to add `qt_documentation = 'Qt5'` to my `conf.py` in that project to work around this same problem. (And `'PyQt5': ('https://www.riverbankcomputing.com/static/Docs/PyQt5', None),` to `intersphinx_mapping`.)

**Comment by ssokolow** [comment]
Since 16.04 is no longer supported and I'm no longer on it, this can be closed.

(And sorry for just assuming you'd reply and putting this out of mind.)

**Comment by Czaki** [comment]
I have long working days these times and forget about this. I'm sorry. I'm sorry to not put this on my todo list immediately.

**Comment by ssokolow** [comment]
No worries. It was my bad anyway. I was the one asking for something and the one who didn't follow up.
