### ISSUE TITLE
QtCore.QEvent.Type

### ISSUE THREAD

**Issue by altendky** [Czaki/sphinx-qt-documentation#7]
References to `QtCore.QEvent.Type` fail to be handled.  References to `QtCore.QEvent` are fine.

`QtCore.QEvent` links to: https://doc.qt.io/qt-5/qevent.html
`QtCore.QEvent.Type` should link to: https://doc.qt.io/qt-5/qevent.html#Type-enum

https://github.com/altendky/qtrio/pull/93/checks?check_run_id=863919645
`/home/runner/work/qtrio/qtrio/qtrio/_core.py:docstring of qtrio.registered_event_type:5:py:class reference target not found: PySide2.QtCore.QEvent.Type`

https://github.com/altendky/qtrio/pull/93/files#diff-aca67cae4ab3db4c745d891483802bf2R37
```python
def registered_event_type() -> typing.Optional[QtCore.QEvent.Type]:
```

Not right at the moment, but maybe I can find some time to learn about this system and submit a PR.  Of course, thank you for everything that does work.  `:]`

**Comment by Czaki** [comment]
Strange. There is entry for this in inv file. 
```
	PyQt5.QtCore.QEvent.Type                 Type                                    : api/qtcore/qevent.html##Type
```
I do not have idea how to solve it fast. One option is to use conditional breakpoint and check what happen if `target` contains `QEvent.Type` is processed. 

https://github.com/Czaki/sphinx-qt-documentation/blob/6a45ff086b0d743891760380eca4a5766a72c591/sphinx_qt_documentation/__init__.py#L73
 
I will try to debug this, but I'm it may take few days. So If you have time I'm open on PR.

**Comment by altendky** [comment]
Welp, maybe I jumped too far in my conclusions.  I'll let you know what I find either way.  Thanks for the quick followup.

**Comment by altendky** [comment]
`obj_type_name` is `'sip:class'` but it is `sip:enum` in the `.inv`.

```
PyQt5.QtCore.QEvent.Type sip:enum 0 api/qtcore/qevent.html##Type Type
```

I'm not experienced with sphinx yet but the first thing that strikes my mind is that I should write `` :sip:enum:`QtCore.QEvent.Type` `` (or something along those lines) but this is from a type hint that is added to the docs by `sphinx-autodoc-typehints` so I can't exactly add that.

I don't know if this is a sensible fix but tweaking to the following gets me a link to https://doc.qt.io/qt-5/qevent.html#Type at least.

```python
type_translate_dict = {
    "class": ["class", "enum"],
    "meth": ["method", "signal"],
    "mod": ["module"],
}
```
So, one step closer but still missing the -enum in the URL.  A quick little hack covers that and I get a working link.

```python
if name == 'enum':
    uri += "-enum"
```

As I said, I have no idea if this is garbage or the proper fix.  But, I'll submit a PR in a few minutes here so it's a solid thing to look at rather than little snippets here.
